name: Develop Branch CI

on:
  pull_request:
    branches: [ develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Type check
        run: npx tsc --noEmit

      - name: Run unit tests
        run: npm test -- --watch=false --browsers=ChromeHeadless

      # - name: Check code formatting
      #   run: npx prettier --check .

      - name: Build Angular app
        run: npm run build -- --configuration=production

      - name: Check outdated dependencies
        run: npx npm-check-updates --errorLevel 2
        continue-on-error: true